- name: copy s3.conf
  template:
    src: s3.j2
    dest: /root/s3.conf
    owner: root
    group: root
    mode: 0644
    
- name: run nginx container
  shell: docker run -d --net=host -v /root/s3.conf:/etc/nginx/conf.d/s3.conf --name nginx-proxy nginx