# ansible

ansible_ssh_user: fedora
ansible_ssh_private_key_file:
ansible_python_interpreter: /usr/bin/python3
# Kubernetes

token: c9f7b8.8d17974y63l7g85s
pod_network_cidr: "10.244.0.0/16"

# passwords

mariadb_root_password: CkZAy42zuykED9Nb
mariadb_keystone_password: trrc6PCOFPlKRR&R
mongodb_admin_password: trrc6PCOFPlKRR&R
mongodb_swygate_password: o3LqdQqfSb0lm98T
mongodb_swyadmd_password: PM@KjvrWEtAmUBNq
mongodb_s3_password: HfnuaVea7fz3fz0o
keystone_swyadmin_password: EC@K6grYWaG0urMn
keystone_swyui_password: DbeofMUkvt$pmHsL
keystone_admin_password: V7WBwe4AE3midEXR #without special chars
keystone_swydbscr_password: XV1he51aI35MjR
rabbitmq_root_password: ls8RmtuuXcYJA5Mr
rabbitmq_s3_password: MHCCOhozTrTjTRk
pgr_token: wnUXzg3BiNIdU1g
s3_token: em0pP8KE6X2KuRv
s3_secret_key: 60c0b0cae645a2768405dd8ff9f9a14e
mw_secpass: 00e18d1b513b69ac066ad0cb45cb1515

remote_host_ip: '%'

# tinc vpn

netname: nyc3
vpn_interface: tun0
physical_ip: "{{ ansible_eth0_0.ipv4.address }}"
tinc_vpn_ip: "{{ ansible_eth1.ipv4.address }}"
host_min: 10.133.0.0
vpn_netmask: 255.255.255.0
vpn_subnet_cidr_netmask: 32

# let's encrypt

cert_admin_email: serenityqn@gmail.com

# for customization of this, use --extra-vars and omit "default_" in key, otherwise default will be applied
default_dashboard_domain_name: dashboard-dev.swifty.cloud
default_api_domain_name: api-dev.swifty.cloud
default_s3_domain_name: s3-dev.swifty.cloud

# docker

registry_host: registry.gitlab.com
docker_username: gitlab+deploy-token-27648
docker_password: bejaxhFt9LWnSJZT59xy

# system

systemd_dir: /lib/systemd/system
system_env_dir: /etc/sysconfig
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf
kube_addon_dir: /etc/kubernetes/addon
