# ansible

ansible_ssh_user: fedora
ansible_ssh_private_key_file:
ansible_python_interpreter: /usr/bin/python3
# Kubernetes

token: c9f7b8.8d17974y63l7g85s
pod_network_cidr: "10.244.0.0/16"

# passwords

mariadb_root_password: a5d8bfe6979a
mariadb_keystone_password: N9tSc5kgtKqvwRwN
mongodb_admin_password: ew8VKv8Kq79C
mongodb_swygate_password: dt3962zew1b
mongodb_swyadmd_password: 1a84cd9148bG8
mongodb_s3_password: aebik0eichie0eXu
keystone_swyadmin_password: PwE9eMcPAverUJZn
keystone_swyui_password: HEMv3b6GnCGt2XTn
keystone_admin_password: 789qt4htqg5PkbXC
keystone_swydbscr_password: NWJIfQtPDdMCliU2
rabbitmq_root_password: 1OqCKIK2G9H
rabbitmq_s3_password: 60baf87b7407
pgr_token: e8yftKPn_GrhFa0d9TMwCt7GG?Ggu:biw:e_bfndvfyC^i-D*=+*euNznmpxE1jq
s3_token: NgsfqX&ruOcjk+CXr@a2yq_M-YAGv7^#-6?E=zw:Rh?FJf_fWVfivHKi1A?m2jDR
s3_secret_key: fd7b1601ae2ff4ccb91b85ea315f2b2e
mw_secpass: f406a11cd8598e80b6180230f116b15b

remote_host_ip: '%'

# aws

ec2_keypair: "ansible"
ec2_instance_type: "t2.medium"
ec2_image: "ami-005ca2b3c05cf85e2"
ec2_region: "us-east-1"
ec2_vpc_id: "vpc-2766af5c"

# tinc vpn

netname: nyc3
vpn_interface: tun0
physical_ip: "{{ ansible_eth0.ipv4.address }}"
tinc_vpn_ip: "{{ ansible_tun0.ipv4.address }}"
vpn_netmask: 255.255.255.0
vpn_subnet_cidr_netmask: 32

# let's encrypt

cert_admin_email: serenityqn@gmail.com

# for customization of this, use --extra-vars and omit "default_" in key, otherwise default will be applied
default_dashboard_domain_name: dashboard-dev.swifty.cloud
default_api_domain_name: api-dev.swifty.cloud
default_s3_domain_name: s3-dev.swifty.cloud

# docker

registry_host: registry.gitlab.com
docker_username: gitlab+deploy-token-27648
docker_password: bejaxhFt9LWnSJZT59xy

# system

systemd_dir: /lib/systemd/system
system_env_dir: /etc/sysconfig
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf
kube_addon_dir: /etc/kubernetes/addon
