# ansible

ansible_ssh_user: fedora
ansible_ssh_private_key_file: ./ansible.pem

# Kubernetes

token: c9f7b8.8d17974y63l7g85s
pod_network_cidr: "10.244.0.0/16"

# passwords

mariadb_root_password: a5d8bfe6979a
mariadb_keystone_password: N9tSc5kgtKqvwRwN
mongodb_admin_password: ew8VKv8Kq79C
mongodb_swygate_password: dt3962zew1b
mongodb_swyadmd_password: 1a84cd9148bG8
mongodb_s3_password: aebik0eichie0eXu
keystone_swyadmin_password: PwE9eMcPAverUJZn
keystone_swyui_password: HEMv3b6GnCGt2XTn
keystone_admin_password: 789qt4htqg5PkbXC
rabbitmq_root_password: 1OqCKIK2G9H
rabbitmq_s3_password: 60baf87b7407
pgr_token: e8yftKPn_GrhFa0d9TMwCt7GG?Ggu:biw:e_bfndvfyC^i-D*=+*euNznmpxE1jq
s3_token: NgsfqX&ruOcjk+CXr@a2yq_M-YAGv7^#-6?E=zw:Rh?FJf_fWVfivHKi1A?m2jDR
s3_secret_key: fd7b1601ae2ff4ccb91b85ea315f2b2e
mw_secpass: f406a11cd8598e80b6180230f116b15b

remote_host_ip: '%'

# aws

ec2_keypair: "ansible"
ec2_security_group: "sg-e0fe9c8a"
ec2_instance_type: "t2.medium"
ec2_image: "ami-e4a89a81"
ec2_subnet_id: "subnet-a7cf72cf"
ec2_region: "us-east-2"

# system

systemd_dir: /lib/systemd/system
system_env_dir: /etc/sysconfig
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf
kube_addon_dir: /etc/kubernetes/addon
