- name: install libselinux
  dnf:
    name: libselinux-python3
    state: latest

- name: Disable selinux
  selinux:
    state: disabled

- name: Install the mysqlclient module
  pip:
    name: docker-py
    executable: pip3

- name: install docker engine
  dnf:
    name: docker
    state: latest
- name: enable  docker service
  systemd:
    name: docker
    enabled: yes
    masked: no

- name: start docker service
  systemd: state=started name=docker

- name: Log into swifty registry
  shell: "docker login {{ registry_host }} -u {{ docker_username }} -p {{ docker_password }}"
