- name: Disable selinux
  shell: "setenforce 0"
  
- name: install docker engine
  dnf:
    name: docker
    state: latest
- name: enable  docker service
  systemd:
    name: docker
    enabled: yes
    masked: no
- name: start docker service
  systemd: state=started name=docker
