---
- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
   - include_vars: group_vars/all.yml
  roles:
   - ec2

- hosts: swy-core
  gather_facts: true
  become: yes
  become_method: sudo
  pre_tasks:
   - include_vars: group_vars/all.yml
  roles:
   - docker
   - { role: k8s/master, tags: master}
   - mariadb
   - mongod
   - rabbitmq
   - openstack-keystone
   - { role: nfs/master, tags: master}

- hosts: swy-worker
  gather_facts: true
  become: yes
  become_method: sudo
  pre_tasks:
   - include_vars: group_vars/all.yml
  roles:
   - docker
   - { role: k8s/worker, tags: worker}
   - { role: nfs/client, tags: client}
